services:
  - type: web
    name: your-frontend-app
    env: static
    buildCommand: npm install && npm run build
    publishDir: ./dist
    staticPublishPath: ./dist
    routes:
      - type: static
        source: ./Public/firebase-messaging-sw.js
        destination: ./Public/firebase-messaging-sw.js